
The following have been reloaded with a version change:
  1) CUDA/10.1.243 => CUDA/10.0.130


Lmod is automatically replacing "GCC/8.3.0" with "iccifort/2019.5.281".


Lmod is automatically replacing "GCC/8.3.0" with "iccifort/2019.5.281".


The following have been reloaded with a version change:
  1) CUDA/10.0.130 => CUDA/10.1.243

Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "NCCL/2.6.4"
   Try: "module spider NCCL/2.6.4" to see how to load the module(s).



Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "Python/3.6.4"
   Try: "module spider Python/3.6.4" to see how to load the module(s).



GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
Fatal Python error: Bus error

Current thread 0x00002b624581fa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002ab04b009a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightningFatal Python error: Bus error

Current thread 0x00002b2fa74b2a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002ab604c27a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002b3e1ba5aa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002b5e6ca34a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modFatal Python error: Segmentation fault

Current thread 0x00002b9954538a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002ba554be7a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002acecb1dfa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/pythules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/modon3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
ule.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Bus error

Current thread 0x00002ba33dd2ea00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "lightning_TF_train.py", line 185 in main
  File "lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002b3fdd839a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002af8cebb6a00 (most recent call first):
Fatal Python error: Bus error

Current thread 0x00002accca60aa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
Fatal Python error: Bus error

Current thread 0x00002ad38bc5aa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "lightning_TF_train.py", line 185 in main
  File "lightning_TF_train.py", line 191 in <module>
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002abe824c7a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
Fatal Python error: Segmentation fault

Current thread 0x00002aff3da8fa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "lightning_TF_train.py", line 185 in main
  File "lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002b454eb0aa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pyFatal Python error: torch_lightning/plugins/training_type/Segmentation faultd

dpCurrent thread 0x.00002ab48f2e0a00p (most recent call first):
y  File ", line "286 in /mmondte/lh_otmoe_/drevaimcees
h  File s"5//mantn/acondhao3m/el/irba/mpeysthhon3s.58//saintaec-opndaac3k/algiebs//ptyotrhcohn/n3n./8m/osidultees-/pmackaodule.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modges/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
ules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "lightning_TF_train.py", line 185 in main
  File "lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002b21b3d5ba00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Fatal Python error: Bus error

Current thread 0x00002b6ebf762a00 (most recent call first):
Current thread 0x00002b219367fa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
Fatal Python error: Bus error

Current thread 0x00002b32a8a61a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00002b8c9b091a00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "lightning_TF_train.py", line 185 in main
  File "lightning_TF_train.py", line 191 in <module>
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
Fatal Python error: Segmentation fault

Current thread 0x00002b9fc093aa00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py"Fatal Python error: Segmentation fault

Current thread 0x00002b5c0367ca00 (most recent call first):
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anacond, line 671 in convert
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py"a3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
, line 387 in _apply
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120 in to
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89 in inner_fn
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286 in model_to_device
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524 in pre_dispatch
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495 in fit
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185 in main
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191 in <module>
initializing ddp: GLOBAL_RANK: 5, MEMBER: 6/6
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "lightning_TF_train.py", line 191, in <module>
    main(args)
  File "lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=21216054.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: nvl-003: task 11: Out Of Memory
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "lightning_TF_train.py", line 191, in <module>
    main(args)
  File "lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "lightning_TF_train.py", line 191, in <module>
    main(args)
  File "lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "lightning_TF_train.py", line 191, in <module>
    main(args)
  File "lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "lightning_TF_train.py", line 191, in <module>
    main(args)
  File "lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 191, in <module>
    main(args)
  File "/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/lightning_TF_train.py", line 185, in main
    trainer.fit(model, train_loader, val_loader)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in fit
    self.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 524, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 83, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 261, in pre_dispatch
    self.model_to_device()
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 286, in model_to_device
    self.model.to(self.root_device)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/decorators.py", line 89, in inner_fn
    module = fn(self, *args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 120, in to
    return super().to(*args, **kwargs)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
Fatal Python error: Bus error

Current thread 0x00002aed6eb98a00 (most recent call first):
<no Python frame>
Fatal Python error: Bus error

Fatal Python error: Segmentation fault

Current thread 0x00002afc36505a00 (most recent call first):
Current thread 0x00002b4c39e9da00 (most recent call first):
<no Python frame>
Fatal Python error: Bus error

Fatal Python error: Bus error

  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671 in convert
Current thread 0x00002ad89ddd8a00 (most recent call first):
<no Python frame>
Fatal Python error: Fatal Python error: Bus error

Current thread 0x00002aad4e57da00 (most recent call first):
slurmstepd: error: Detected 6701 oom-kill event(s) in StepId=21216054.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
  File "/mnt/home/rameshs5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line slurmstepd: error: Detected 3904 oom-kill event(s) in StepId=21216054.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
Fatal Python error: Bus errorFatal Python error: JobId=21216054 JobName=run_script2.sh
   UserId=rameshs5(1006700) GroupId=cmse(2362) MCS_label=N/A
   Priority=47833 Nice=0 Account=wang-krishnan QOS=normal
   JobState=RUNNING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:02:55 TimeLimit=03:59:00 TimeMin=N/A
   SubmitTime=2021-04-14T14:29:11 EligibleTime=2021-04-14T14:29:11
   AccrueTime=2021-04-14T14:29:11
   StartTime=2021-04-14T17:37:36 EndTime=2021-04-14T21:36:36 Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2021-04-14T17:37:34
   Partition=general-short AllocNode:Sid=dev-amd20-v100:258504
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=nvl-[002-004]
   BatchHost=nvl-002
   NumNodes=3 NumCPUs=18 NumTasks=18 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=18,mem=75G,node=3,billing=11673,gres/gpu=18
   Socks/Node=* NtasksPerN:B:S:C=6:0:*:* CoreSpec=*
   MinCPUsNode=6 MinMemoryNode=25G MinTmpDiskNode=0
   Features=[intel14|intel16|intel18|amr|nvf] DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/run_script2.sh
   WorkDir=/mnt/ufs18/home-118/rameshs5/TFNet_Optimization
   Comment=stdout=/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/srun_3_nodes_6_gpus.out 
   StdErr=/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/srun_3_nodes_6_gpus.out
   StdIn=/dev/null
   StdOut=/mnt/ufs18/home-118/rameshs5/TFNet_Optimization/srun_3_nodes_6_gpus.out
   Power=
   TresPerNode=gpu:v100:6
   NtasksPerTRES:0

slurmstepd: error: Detected 6701 oom-kill event(s) in StepId=21216054.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
